[package]
name = "gl"
version = "0.5.0"
authors = ["Brendan Zabarauskas <bjzaba@yahoo.com.au>",
        "Corey Richardson",
        "Arseny Kapoulkine"
]
description = "OpenGL bindings"
license = "Apache-2.0"
build = "build.rs"
repository = "https://github.com/bjz/gl-rs/"

[build-dependencies.gl_generator]
path = "../gl_generator"
version = "0.4.0"

[build-dependencies.khronos_api]
path = "../khronos_api"
version = "0.0.8"

[dev-dependencies]
glutin = "0.4"
